name: Generate Resume

on:
  push:
    branches: [ "master" ]
    paths: [ "resume.latex" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Generate Resume
      uses: dante-ev/latex-action@latest
      with:
        root_file: resume.latex
        compiler: pdflatex
        args: -interaction=nonstopmode -shell-escape

    - name: Rename PDF
      run: mv resume.pdf Aditya_Kurdunkar_Resume.pdf

    - name: Commit Resume
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Generate Aditya_Kurdunkar_Resume.pdf

    - name: Release PDF
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "latest"
        title: "Resume: ${{ github.sha }}"
        files: |
          Aditya_Kurdunkar_Resume.pdf
